apiVersion: v1
kind: Template
metadata:
  name: mlbparks-dev-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: mlbparks
    name: mlbparks
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/${GUID}-parks-dev/mlbparks:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mlbparks-config
  data:
    db_host: ${DB_HOST}
    db_port: ${DB_PORT}
    db_username: ${DB_USERNAME}
    db_password: ${DB_PASSWORD}
    db_name: ${DB_NAME}
    app_name: "MLB Parks (Dev)"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mlbparks
    name: mlbparks
  spec:
    replicas: 1
    selector:
      app: mlbparks
      deploymentconfig: mlbparks
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
        post:
          execNewPod:
            command:
            - /bin/sh
            - -c
            - curl http://mlbparks:8080/ws/data/load/
            containerName: mlbparks
          failurePolicy: ignore
      type: Rolling
    template:
      metadata:
        labels:
          app: mlbparks
          deploymentconfig: mlbparks
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: mlbparks
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mlbparks-config
                key: db_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: mlbparks-config
                key: db_port
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mlbparks-config
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mlbparks-config
                key: db_password
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mlbparks-config
                key: db_name
          - name: APPNAME
            valueFrom:
              configMapKeyRef:
                name: mlbparks-config
                key: app_name
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: mlbparks
    name: mlbparks
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mlbparks:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.7
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: mlbparks
    name: mlbparks
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: mlbparks
      weight: 100
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mlbparks
      type: parksmap-backend
    name: mlbparks
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: mlbparks
      deploymentconfig: mlbparks
    sessionAffinity: None
    type: ClusterIP
parameters:
- name: GUID
  displayName: GUID
  description: guid
  value: 46b9
  required: true
- name: DB_HOST
  displayName: DB_HOST
  description: db host
  value: mongodb
  required: true
- name: DB_PORT
  displayName: DB_PORT
  description: db port
  value: "27017"
  required: true
- name: DB_USERNAME
  displayName: DB_USERNAME
  description: db username
  value: mongodb
  required: true
- name: DB_PASSWORD
  displayName: DB_PASSWORD
  description: db password
  value: mongodb
  required: true
- name: DB_NAME
  displayName: DB_NAME
  description: db name
  value: parks
  required: true
