
apiVersion: v1
kind: Template
metadata:
  name: mongodb-statefulset-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: mongodb
    labels:
      name: mongodb
  spec:
    ports:
    - port: 27017
      name: mongodb
    selector:
      name: mongodb
- apiVersion: v1
  kind: Service
  metadata:
    name: mongodb-internal
    labels:
      name: mongodb
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  spec:
    ports:
    - port: 27017
      name: mongodb
    clusterIP: None
    selector:
      name: "mongodb"
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mongodb
  spec:
    selector:
      matchLabels:
        name: mongodb # must match .spec.template.metadata.labels
    serviceName: mongodb-internal
    replicas: 3
    template:
      metadata:
        labels:
          name: mongodb # must match .spec.selector.matchLabels
      spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: mongodb
          image: registry.access.redhat.com/rhscl/mongodb-32-rhel7:3.2
          ports:
          - containerPort: 27017
            name: mongodb
          args:
          - run-mongod-replication
          volumeMounts:
          - name: mongo-data
            mountPath: /var/lib/mongodb/data
          env:
          - name: MONGODB_DATABASE
            value: ${MONGODB_DATABASE}
          - name: MONGODB_USER
            value: ${MONGODB_USER}
          - name: MONGODB_PASSWORD
            value: ${MONGODB_PASSWORD}
          - name: MONGODB_ADMIN_PASSWORD
            value: ${MONGODB_ADMIN_PASSWORD}
          - name: MONGODB_REPLICA_NAME
            value: ${MONGODB_REPLICA_NAME}
          - name: MONGODB_KEYFILE_VALUE
            value: "${MONGODB_KEYFILE_VALUE}"
          - name: MONGODB_SERVICE_NAME
            value: mongodb-internal
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          readinessProbe:
              exec:
                command:
                  - stat
                  - /tmp/initialized
    volumeClaimTemplates:
      - metadata:
          name: mongo-data
          labels:
            name: "mongodb"
        spec:
          accessModes: [ ReadWriteOnce ]
          resources:
            requests:
              storage: "${VOLUME_CAPACITY}"
parameters:
- name: MONGODB_USER
  displayName: MONGODB_USER
  description: mongodb username
  value: mongodb
  required: true
- name: MONGODB_PASSWORD
  displayName: MONGODB_PASSWORD
  description: mongodb password
  value: mongodb
  required: true
- name: MONGODB_DATABASE
  displayName: MONGODB_DATABASE
  description: mongodb database
  value: newdb
  required: true
- name: MONGODB_ADMIN_PASSWORD
  displayName: MONGODB_ADMIN_PASSWORD
  description: mongodb admin password
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: MONGODB_REPLICA_NAME
  displayName: MONGODB_REPLICA_NAME
  description: mongodb replica name
  value: rs0
  required: true
- name: MONGODB_KEYFILE_VALUE
  displayName: MONGODB_KEYFILE_VALUE
  description: mongodb keyfile value
  value: "12345678901234567890"
  required: true
- name: VOLUME_CAPACITY
  displayName: VOLUME_CAPACITY
  description: volume capacity
  value: "1Gi"
- name: MEMORY_LIMIT
  displayName: MEMORY_LIMIT
  description: memory limit
  value: "512Mi"
