apiVersion: v1
kind: Template
metadata:
  name: parksmap-prod-template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: parksmap-green-config
  data:
    app_name: "ParksMap (Green)"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: parksmap-blue-config
  data:
    app_name: "ParksMap (Blue)"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: parksmap-green
    name: parksmap-green
  spec:
    replicas: 1
    selector:
      app: parksmap-green
      deploymentconfig: parksmap-green
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: parksmap-green
          deploymentconfig: parksmap-green
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: parksmap-green
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: APPNAME
            valueFrom:
              configMapKeyRef:
                name: parksmap-green-config
                key: app_name
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: parksmap-blue
    name: parksmap-blue
  spec:
    replicas: 1
    selector:
      app: parksmap-blue
      deploymentconfig: parksmap-blue
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: parksmap-blue
          deploymentconfig: parksmap-blue
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: parksmap-blue
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: APPNAME
            valueFrom:
              configMapKeyRef:
                name: parksmap-blue-config
                key: app_name
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: parksmap-green
    name: parksmap
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: parksmap-green
      weight: 100
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: parksmap-green
    name: parksmap-green
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: parksmap-green
      deploymentconfig: parksmap-green
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: parksmap-blue
    name: parksmap-blue
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: parksmap-blue
      deploymentconfig: parksmap-blue
    sessionAffinity: None
    type: ClusterIP
parameters:
